---
# List of common datasets managed directly
zfs_setup_datasets:
  - name: zroot/Reserved
    properties:
      refreservation: 100G

  - name: zroot/ROOT
    properties:
      exec: on
      setuid: on
      devices: on
      org.zfsbootmenu:active: on
      org.zfsbootmenu:commandline: "quiet"

  - name: zroot/data
    properties:
      exec: on
      mountpoint: /home
      canmount: no

  - name: zroot/data/jj
    properties:
      canmount: no

  - name: zroot/data/jj/Vaults
    properties:
      recordsize: 16K
      compression: zstd-1
      systemd.after: home-jj.mount
      exec: off

  - name: zroot/data/jj/Downloads
    properties:
      systemd.after: home-jj.mount

  - name: zroot/data/jj/Code
    properties:
      recordsize: 16K
      compression: zstd-1
      systemd.after: home-jj.mount

  - name: zroot/data/jj/Media
    properties:
      recordsize: 1M
      compression: zle
      systemd.after: home-jj.mount
      exec: off

  - name: zroot/data/jj/Books
    properties:
      recordsize: 64K
      compression: zstd-1
      systemd.after: home-jj.mount
      exec: off

  - name: zroot/data/jj/flatpak
    properties:
      mountpoint: /home/jj/.var
      systemd.after: home-jj.mount

  - name: zroot/data/leah
    properties:
      canmount: no

  - name: zroot/data/leah/Documents
    properties:
      recordsize: 16K
      compression: zstd-1
      systemd.after: home-leah.mount

  - name: zroot/data/leah/Downloads
    properties:
      systemd.after: home-leah.mount

  - name: zroot/data/leah/Media
    properties:
      recordsize: 1M
      compression: zle
      systemd.after: home-leah.mount

  - name: zroot/data/leah/flatpak
    properties:
      mountpoint: /home/leah/.var
      systemd.after: home-leah.mount

  - name: zroot/data/Shared
    properties:
      mountpoint: /home/Shared
      exec: off

  - name: zroot/data/Shared/Documents
    properties:
      recordsize: 16K
      compression: zstd-1

  - name: zroot/data/Shared/Music
    properties:
      recordsize: 1M
      compression: zle

  - name: zroot/data/Shared/Pictures
    properties:
      recordsize: 1M
      compression: zle

  - name: zroot/virt
    properties:
      exec: on
      devices: on
      setuid: on
      mountpoint: /var/lib
      canmount: no

  - name: zroot/virt/docker
    properties: {}

  - name: zroot/virt/podman
    properties: {}

  - name: zroot/virt/libvirt
    properties:
      recordsize: 1M
      compression: zle

  - name: zroot/pkgs
    properties:
      exec: on

  - name: zroot/pkgs/flatpak
    properties:
      mountpoint: /var/lib/flatpak

  - name: zroot/pkgs/nix
    properties:
      mountpoint: /nix

# List of distroids (distro IDs) to manage
zfs_setup_distroids:
  - manjaro
  - arch
  - debian

# Relative datasets to create for each distroid
zfs_setup_distroid_datasets:
  - name: ""
    properties:
      mountpoint: /
      canmount: noauto
      org.zfsbootmenu:bootfs: on
  - name: var
    properties:
      mountpoint: none
      exec: off
      devices: off
      setuid: off
  - name: var/log
    properties:
      mountpoint: legacy
    legacy_mount: /var/log
  - name: home
    properties:
      devices: off
      setuid: off
      mountpoint: none
  - name: home/jj
    properties:
      mountpoint: legacy
    legacy_mount: /home/jj
  - name: home/leah
    properties:
      mountpoint: legacy
    legacy_mount: /home/leah

zfs_setup_pools:
  - zroot
  - zarchive-4
  - zarchive-5

zfs_setup_hostid: dadab0de

zfs_setup_list_cacher_target: /usr/lib/zfs-linux/zed.d/history_event-zfs-list-cacher.sh
zfs_setup_list_cacher_symlink: /etc/zfs/zed.d/history_event-zfs-list-cacher.sh
