---
# List of common datasets managed directly
zfs_datasets:
  - name: zroot/Reserved
    properties:
      refreservation: 100G

  - name: zroot/ROOT
    properties:
      exec: on
      setuid: on
      devices: on
      org.zfsbootmenu:active: on
      org.zfsbootmenu:commandline: "quiet"

  - name: zroot/home
    properties:
      exec: on
      mountpoint: /home
      canmount: no

  - name: zroot/home/jj
    properties:
      canmount: no

  - name: zroot/home/jj/Vaults
    properties:
      recordsize: 16K
      compression: zstd-1
      systemd.after: home-jj.mount
      exec: off

  - name: zroot/home/jj/Downloads
    properties:
      systemd.after: home-jj.mount

  - name: zroot/home/jj/Code
    properties:
      recordsize: 16K
      compression: zstd-1
      systemd.after: home-jj.mount

  - name: zroot/home/jj/Media
    properties:
      recordsize: 1M
      compression: zle
      systemd.after: home-jj.mount
      exec: off

  - name: zroot/home/jj/Books
    properties:
      recordsize: 64K
      compression: zstd-1
      systemd.after: home-jj.mount
      exec: off

  - name: zroot/home/jj/flatpak
    properties:
      mountpoint: /home/jj/.var
      systemd.after: home-jj.mount

  - name: zroot/home/leah
    properties:
      canmount: no

  - name: zroot/home/leah/Documents
    properties:
      recordsize: 16K
      compression: zstd-1
      systemd.after: home-leah.mount

  - name: zroot/home/leah/Downloads
    properties:
      systemd.after: home-leah.mount

  - name: zroot/home/leah/Media
    properties:
      recordsize: 1M
      compression: zle
      systemd.after: home-leah.mount

  - name: zroot/home/leah/flatpak
    properties:
      mountpoint: /home/leah/.var
      systemd.after: home-leah.mount

  - name: zroot/home/Shared
    properties:
      mountpoint: /home/Shared
      exec: off

  - name: zroot/home/Shared/Documents
    properties:
      recordsize: 16K
      compression: zstd-1

  - name: zroot/home/Shared/Music
    properties:
      recordsize: 1M
      compression: zle

  - name: zroot/home/Shared/Pictures
    properties:
      recordsize: 1M
      compression: zle

  - name: zroot/virt
    properties:
      exec: on
      devices: on
      setuid: on
      mountpoint: /var/lib
      canmount: no

  - name: zroot/virt/docker
    properties: {}

  - name: zroot/virt/podman
    properties: {}

  - name: zroot/virt/libvirt
    properties:
      recordsize: 1M
      compression: zle

  - name: zroot/pkgs
    properties:
      exec: on

  - name: zroot/pkgs/flatpak
    properties:
      mountpoint: /var/lib/flatpak

  - name: zroot/pkgs/nix
    properties:
      mountpoint: /nix

# List of distroids (distro IDs) to manage
zfs_distroids:
  - manjaro
  - arch
  - debian

# Relative datasets to create for each distroid
zfs_distroid_datasets:
  - name: ""
    properties:
      mountpoint: /
      canmount: noauto
      org.zfsbootmenu:bootfs: on
  - name: var
    properties:
      mountpoint: none
      exec: off
      devices: off
      setuid: off
  - name: var/log
    properties:
      mountpoint: legacy
    legacy_mount: /var/log
  - name: home
    properties:
      devices: off
      setuid: off
      mountpoint: none
  - name: home/jj
    properties:
      mountpoint: legacy
    legacy_mount: /home/jj
  - name: home/leah
    properties:
      mountpoint: legacy
    legacy_mount: /home/leah

sanoid_templates:
  template_system:
    hourly: 24
    daily: 7
    weekly: 4
    monthly: 3
    autosnap: 'yes'
    autoprune: 'yes'
  template_data:
    hourly: 48
    daily: 30
    weekly: 12
    monthly: 12
    autosnap: 'yes'
    autoprune: 'yes'
  template_archive_system:
    daily: 30
    monthly: 3
    yearly: 1
    autosnap: 'no'
    autoprune: 'yes'
  template_archive_data:
    daily: 168   # 6 months
    monthly: 12
    yearly: 2
    autosnap: 'no'
    autoprune: 'yes'
