---
# defaults/backup.yml

sanoid_datasets:
  - name: zroot
    template: system
  - name: zroot/data
    template: data

sanoid_distroid_datasets:
  - name: home
    template: data
  # add more if needed (e.g., for /var/log, etc.)

sanoid_templates:
  system:
    hourly: 24
    daily: 7
    weekly: 4
    monthly: 3
    autosnap: 'yes'
    autoprune: 'yes'
  data:
    hourly: 48
    daily: 30
    weekly: 12
    monthly: 12
    autosnap: 'yes'
    autoprune: 'yes'
  archive_system:
    daily: 30
    monthly: 3
    yearly: 1
    autosnap: 'no'
    autoprune: 'yes'
  archive_data:
    daily: 168   # 6 months
    monthly: 12
    yearly: 2
    autosnap: 'no'
    autoprune: 'yes'
