---
- name: ZFS Setup tasks
  ansible.builtin.import_tasks: zfs_configure.yml
  tags: zfs_setup_configure

- name: ZFS Snapshots and Replications
  ansible.builtin.import_tasks: zfs_backup.yml
  tags: zfs_setup_backup

- name: ZFS Scrub tasks
  ansible.builtin.import_tasks: zfs_scrub.yml
  tags: zfs_setup_scrub
