---
- name: Import dataset tasks
  ansible.builtin.import_tasks: zfs_datasets.yml
  tags: zfs_datasets

- name: ZFS Setup tasks
  ansible.builtin.import_tasks: zfs_configure.yml
  tags: zfs_configure
