---
- name: Ensure /etc/zfs exists
  ansible.builtin.file:
    path: /etc/zfs
    state: directory
    mode: '0755'

- name: Ensure /etc/zfs/zfs-list.cache exists
  ansible.builtin.file:
    path: /etc/zfs/zfs-list.cache
    state: directory
    mode: '0755'

- name: Ensure zfs-list.cache file for all pools exists
  ansible.builtin.file:
    path: "/etc/zfs/zfs-list.cache/{{ item }}"
    state: touch
    mode: '0644'
  loop: "{{ zfs_setup_pools }}"

- name: Ensure symlink for history_event-zfs-list-cacher.sh exists and is correct
  ansible.builtin.file:
    src: "{{ zfs_setup_list_cacher_target }}"
    dest: "{{ zfs_setup_list_cacher_symlink }}"
    state: link
    force: true

# Loop over all pools for facts and cachefile
- name: Gather ZFS pool facts
  community.general.zpool_facts:
    pool: "{{ item }}"
  register: zpool_facts
  loop: "{{ zfs_setup_pools }}"

- name: Set zpool cachefile if needed for all pools
  ansible.builtin.command: "zpool set cachefile=/etc/zfs/zpool.cache {{ item }}"
  changed_when: false
  when: zpool_facts.results[loop.index0].ansible_facts.ansible_zfs_pools[0].cachefile != "/etc/zfs/zpool.cache"
  loop: "{{ zfs_setup_pools }}"

- name: Stat /etc/hostid
  ansible.builtin.stat:
    path: /etc/hostid
  register: hostid_stat

- name: Slurp /etc/hostid if present
  ansible.builtin.slurp:
    path: /etc/hostid
  register: hostid_slurp
  when: hostid_stat.stat.exists

- name: Compare /etc/hostid to desired value
  ansible.builtin.set_fact:
    hostid_needs_update: >-
      {{
        (not hostid_stat.stat.exists)
        or
        (
          hostid_stat.stat.exists and
          (hostid_slurp.content | b64decode)
          !=
          (zfs_setup_hostid | lower | regex_replace('^0x', '') | to_uuid | to_bytes(length=4, byteorder='big'))
        )
      }}
  when: hostid_stat.stat.exists

- name: Generate /etc/hostid if missing or incorrect
  ansible.builtin.command: "zgenhostid -f {{ zfs_setup_hostid }}"
  changed_when: true
  when: hostid_needs_update | default(true)

- name: Ensure ZFS systemd services are enabled and started
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: true
    state: started
  loop: "{{ zfs_setup_services }}"

- name: Ensure dracut config for ZFS is present
  ansible.builtin.copy:
    dest: /etc/dracut.conf.d/zol.conf
    mode: '0644'
    content: |
      nofsck="yes"
      add_dracutmodules+=" zfs "
      omit_dracutmodules+=" btrfs "
  notify: Regenerate initramfs

- name: Configure ZFS ARC max
  ansible.builtin.copy:
    dest: /etc/modprobe.d/zfs.conf
    content: |
      options zfs zfs_arc_max={{ (ansible_memtotal_mb * 1024 * 1024 * zfs_setup_arc_max_percent) | int }}
    mode: '0644'
  notify: Reload systemd
